### Add resource
POST http://localhost:7071/runtime/webhooks/EventGrid?functionName=EventGridTrigger
Content-Type: application/json

[
    {
        "subject": "/subscriptions/411a9cd0-xxxx-xxxx-xxxx-cc1ea96a3933/resourceGroups/this-is-a-test",
        "eventType": "Microsoft.Resources.ResourceWriteSuccess",
        "eventTime": "2019-12-22T05:11:29.2976486Z",
        "id": "67948585-079c-46d8-badc-c212daa1503c",
        "data": {
            "correlationId": "0a93bfc8-82d1-4b9a-b43d-5125e127ac3c",
            "resourceProvider": "Microsoft.Resources",
            "resourceUri": "/subscriptions/411a9cd0-xxxx-xxxx-xxxx-cc1ea96a3933/resourceGroups/this-is-a-test",
            "operationName": "Microsoft.Resources/subscriptions/resourceGroups/write",
            "status": "Succeeded",
            "subscriptionId": "411a9cd0-xxxx-xxxx-xxxx-cc1ea96a3933",
            "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47"
        },
        "dataVersion": "2",
        "metadataVersion": "1",
        "topic": "/subscriptions/411a9cd0-xxxx-xxxx-xxxx-cc1ea96a3933"
    }
]

### Get sms conversation
GET http://localhost:7071/runtime/webhooks/durabletask/entities/smsconversation/default

### Get resource
GET http://localhost:7071/runtime/webhooks/durabletask/entities/azureresource/test1